version: '3.7'

# https://docs.docker.com/compose/compose-file/#extension-fields
x-shared: &shared
  networks:
    - ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network
  privileged: true # needed for dlv attach
  stop_grace_period: 1m
  security_opt:
    - seccomp:unconfined # https://github.com/arrisray/secql/commit/19b8e85c270b888cecc3a0364b7956ba9e0f5334

networks:
  ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network:
    driver: bridge
    name: ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network

services:

  pre:
    <<: *shared
    image: ${SIMVERSE_DOCKER_IMAGE_PREFIX}${SIMNET_NAME}_pre
    container_name: ${SIMVERSE_DOCKER_CONTAINER_PREFIX}${SIMNET_NAME}_pre
    command: ["run"]
    stop_signal: SIGINT # needed for python server
    build:
      context: .
      dockerfile: docker/pre/Dockerfile
    ports:
      - $SIMVERSE_HOST_BIND$SERVICE_READY_PORT_ON_HOST:$SERVICE_READY_PORT # readiness signal port
    volumes:
      # !DANGER! when touching this, review cookbook.sh > prepare_pre_volumes
      - ./_volumes/certs:/certs # shared certificates
    environment:
      - SERVICE_READY_PORT=${SERVICE_READY_PORT}
      - SIMNET_NAME=${SIMNET_NAME}
    $SIMVERSE_EXTRA_SERVICE_CONFIG
