version: '3.7'

# https://docs.docker.com/compose/compose-file/#extension-fields
x-shared: &shared
  networks:
    - ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network
  privileged: true # needed for dlv attach
  stop_grace_period: 1m
  security_opt:
    - seccomp:unconfined # https://github.com/arrisray/secql/commit/19b8e85c270b888cecc3a0364b7956ba9e0f5334

networks:
  ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network:
    driver: bridge
    name: ${SIMVERSE_DOCKER_NETWORK_PREFIX}${SIMNET_NAME}_network

services:

  _pre:
    <<: *shared
    image: ${SIMVERSE_DOCKER_IMAGE_PREFIX}${SIMNET_NAME}__pre
    container_name: ${SIMVERSE_DOCKER_CONTAINER_PREFIX}${SIMNET_NAME}__pre
    entrypoint: ["./start.sh"]
    stop_signal: SIGINT # needed for python server
    build:
      context: .
      dockerfile: docker/pre/Dockerfile
    ports:
      - $SIMVERSE_HOST_BIND$SIMVERSE_PRE_SIGNAL_PORT_ON_HOST:$SIMVERSE_PRE_SIGNAL_PORT # pre signal port
    volumes:
      # !DANGER! when touching this, review cookbook.sh > prepare_pre_volumes
      - ./_volumes/certs:/certs # shared certificates
    environment:
      - PRE_SIGNAL_PORT=${SIMVERSE_PRE_SIGNAL_PORT}
